In [3]:
import os
os.chdir('/data/ongh0068/l1000/moler_reference')

In [4]:
from molecule_generation.cli.preprocess import _read_data, load_smiles_data
from molecule_generation.utils.preprocessing_utils import save_data

2022-12-13 13:11:20.711860: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
data = _read_data('/data/ongh0068/l1000/raw_smiles_playground/train.smiles')

In [4]:
train_datapoints, valid_datapoints, test_datapoints = load_smiles_data('/data/ongh0068/l1000/raw_smiles_playground')

In [5]:
from molecule_generation.chem.molecule_dataset_utils import featurise_smiles_datapoints

In [6]:
import molecule_generation.chem.motif_utils as motif_utils

featurised_data = featurise_smiles_datapoints(
    train_data = train_datapoints, 
    valid_data = valid_datapoints, 
    test_data = test_datapoints,
    # default values
    motif_extraction_settings= motif_utils.MotifExtractionSettings(
        min_frequency=None,
        min_num_atoms=3,
        cut_leaf_edges=True,
        max_vocab_size=128,
    )
)

100%|███████████████████████████████████████| 100/100 [00:00<00:00, 131.20it/s]


In [7]:
for data in featurised_data.train_data:
    print(data)
    break
    

{'SMILES': 'COC(=O)c1ccc2c(c1)N(Cc1ccccc1)C(=O)c1ccccc1S2(=O)=O', 'mol': <rdkit.Chem.rdchem.Mol object at 0x7fbe8fe28b80>, 'properties': {'sa_score': 2.2193448464743213, 'clogp': 3.466400000000002, 'mol_weight': 407.08274364399995, 'qed': 0.6213092241476093, 'bertz': 1218.9598524227943}, 'motifs': [MotifAnnotation(motif_type='COC=O', atoms=[MotifAtomAnnotation(atom_id=0, symmetry_class_id=0), MotifAtomAnnotation(atom_id=1, symmetry_class_id=3), MotifAtomAnnotation(atom_id=2, symmetry_class_id=2), MotifAtomAnnotation(atom_id=3, symmetry_class_id=1)]), MotifAnnotation(motif_type='C1=CC=CC=C1', atoms=[MotifAtomAnnotation(atom_id=12, symmetry_class_id=0), MotifAtomAnnotation(atom_id=13, symmetry_class_id=0), MotifAtomAnnotation(atom_id=14, symmetry_class_id=0), MotifAtomAnnotation(atom_id=15, symmetry_class_id=0), MotifAtomAnnotation(atom_id=16, symmetry_class_id=0), MotifAtomAnnotation(atom_id=17, symmetry_class_id=0)])], 'graph': {'adjacency_lists': [[(0, 1), (1, 2), (2, 4), (5, 6), (7, 

In [8]:
data

{'SMILES': 'COC(=O)c1ccc2c(c1)N(Cc1ccccc1)C(=O)c1ccccc1S2(=O)=O',
 'mol': <rdkit.Chem.rdchem.Mol at 0x7fbe8fe28b80>,
 'properties': {'sa_score': 2.2193448464743213,
  'clogp': 3.466400000000002,
  'mol_weight': 407.08274364399995,
  'qed': 0.6213092241476093,
  'bertz': 1218.9598524227943},
 'motifs': [MotifAnnotation(motif_type='COC=O', atoms=[MotifAtomAnnotation(atom_id=0, symmetry_class_id=0), MotifAtomAnnotation(atom_id=1, symmetry_class_id=3), MotifAtomAnnotation(atom_id=2, symmetry_class_id=2), MotifAtomAnnotation(atom_id=3, symmetry_class_id=1)]),
  MotifAnnotation(motif_type='C1=CC=CC=C1', atoms=[MotifAtomAnnotation(atom_id=12, symmetry_class_id=0), MotifAtomAnnotation(atom_id=13, symmetry_class_id=0), MotifAtomAnnotation(atom_id=14, symmetry_class_id=0), MotifAtomAnnotation(atom_id=15, symmetry_class_id=0), MotifAtomAnnotation(atom_id=16, symmetry_class_id=0), MotifAtomAnnotation(atom_id=17, symmetry_class_id=0)])],
 'graph': {'adjacency_lists': [[(0, 1),
    (1, 2),
    (2, 4

In [51]:
save_data(featurised_data, output_dir = 'featurised_data_playground')

100%|███████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 109.05it/s]


 Wrote 100 datapoints to featurised_data_playground/train.jsonl.gz.


100%|███████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 118.57it/s]


 Wrote 100 datapoints to featurised_data_playground/valid.jsonl.gz.


100%|███████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 119.79it/s]

 Wrote 100 datapoints to featurised_data_playground/test.jsonl.gz.
 Wrote metadata to featurised_data_playground/metadata.pkl.gz.


In [10]:
import gzip
import pickle

with gzip.open('featurised_data_playground/metadata.pkl.gz', 'rb') as f:
     metadata= pickle.load(f)

In [11]:
metadata

{'train_atom_num_distribution': Counter({29: 4,
          26: 7,
          21: 6,
          30: 5,
          34: 4,
          23: 5,
          11: 1,
          44: 3,
          18: 1,
          25: 8,
          24: 8,
          38: 3,
          35: 4,
          17: 2,
          28: 8,
          41: 1,
          32: 6,
          42: 2,
          19: 4,
          31: 3,
          22: 3,
          27: 1,
          33: 4,
          14: 1,
          20: 2,
          37: 1,
          36: 1,
          50: 1,
          54: 1}),
 'train_atom_type_distribution': Counter({'C': 2113,
          'O': 299,
          'N': 321,
          'S': 29,
          'Cl': 20,
          'F': 30,
          'N+': 9,
          'O-': 9,
          'B': 1,
          'Br': 1}),
 'sa_score_mean': 2.9215050625582446,
 'sa_score_stddev': 0.8425726111747012,
 'clogp_mean': 3.3297466000000013,
 'clogp_stddev': 1.7670030480286232,
 'mol_weight_mean': 395.66346400115987,
 'mol_weight_stddev': 104.36824230378149,
 'qed_mean': 0

In [9]:
from molecule_generation.preprocessing.preprocess import preprocess_jsonl_files
import molecule_generation.preprocessing.generation_order as gen_order
from dpu_utils.utils import RichPath


jsonl_directory = RichPath.create('featurised_data_playground')
trace_directory = RichPath.create('/data/ongh0068/l1000/trace_playground')
preprocess_jsonl_files(
    jsonl_directory=jsonl_directory,
    output_directory=trace_directory,
    tie_fwd_bkwd_edges=True,
    num_processes=1,
    generation_order_cls=gen_order.CanonicalOrder,
    MoLeR_style_trace=True,
    quiet=False,
)

200it [00:00, 6402.39it/s]                                                                                 
Exception ignored in: <function Pool.__del__ at 0x7f12137fa0d0>
Traceback (most recent call last):
  File "/data/ongh0068/anaconda3/envs/l1000/lib/python3.9/multiprocessing/pool.py", line 264, in __del__
    if self._state == RUN:
AttributeError: 'SequentialWorkerPool' object has no attribute '_state'
200it [00:00, 7482.21it/s]                                                                                 
Exception ignored in: <function Pool.__del__ at 0x7f12137fa0d0>
Traceback (most recent call last):
  File "/data/ongh0068/anaconda3/envs/l1000/lib/python3.9/multiprocessing/pool.py", line 264, in __del__
    if self._state == RUN:
AttributeError: 'SequentialWorkerPool' object has no attribute '_state'
200it [00:00, 7189.78it/s]                                                                                 
Exception ignored in: <function Pool.__del__ at 0x7f12137fa0d0>
Traceb

In [5]:
import gzip
import pickle

with gzip.open('/data/ongh0068/l1000/trace_playground/train_0/train_0.pkl.gz', 'rb') as f:
     train= pickle.load(f)




In [4]:
dir(train[0])

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_adjacency_lists',
 '_correct_attachment_point_choices',
 '_correct_edge_choices',
 '_correct_edge_types',
 '_correct_first_node_type_choices',
 '_correct_node_type_choices',
 '_edge_features',
 '_focus_nodes',
 '_graph_property_values',
 '_mol',
 '_node_categorical_features',
 '_node_categorical_num_classes',
 '_node_features',
 '_node_types',
 '_partial_adjacency_lists',
 '_partial_node_categorical_features',
 '_partial_node_features',
 '_type_to_node_to_num_inedges',
 '_valid_attachment_point_choices',
 '_valid_edge_choices',
 '_valid_edge_types',
 'adjacency_lists',
 'correct_attachment_point_choices',
 

In [6]:
train_sample =train[1]

In [70]:
train_sample.node_categorical_features.shape#adjacency_lists

(26,)

In [80]:
import numpy as np
adj_lists = [train_sample.adjacency_lists[i].T for i in range(len(train_sample.adjacency_lists))]
np.concatenate(adj_lists, axis = -1)

array([[ 0,  1,  3,  5,  7,  8,  9, 10, 11, 12, 13, 13, 15, 16, 18, 20,
        21, 23, 24,  7, 22, 11, 25,  1,  2,  4,  6,  8,  9, 10, 11, 12,
        13, 14, 15, 16, 17, 19, 21, 23, 24, 25,  2, 17,  6, 20,  2,  4,
         6, 17, 19, 21,  3,  5,  7, 18, 20, 22],
       [ 1,  2,  4,  6,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 21,
        23, 24, 25,  2, 17,  6, 20,  0,  1,  3,  5,  7,  8,  9, 10, 11,
        12, 13, 13, 15, 16, 18, 20, 21, 23, 24,  7, 22, 11, 25,  3,  5,
         7, 18, 20, 22,  2,  4,  6, 17, 19, 21]], dtype=int32)

In [82]:
np.array([])

array([], dtype=float64)

In [66]:
train_sample.edge_features # edge features refers to the edge features
# for each step in the generation trace, not the edge features of the original graph


[array([], shape=(0, 3), dtype=float32),
 array([[0., 0., 0.]], dtype=float32),
 array([], shape=(0, 3), dtype=float32),
 array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32),
 array([[2., 1., 0.]], dtype=float32),
 array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32),
 array([[3., 1., 0.]], dtype=float32),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32),
 array([[4., 1., 0.],
        [2., 1., 0.]], dtype=float32),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32),
 array([[5., 1., 0.],
        [3., 1., 0.],
        [2., 1., 0.]], dtype=float32),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32),
 array([[6., 1., 0.],
        [4., 1., 0.],
        [3., 1., 0.],
        [2., 1., 0.]], dtype=float32),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
     

In [64]:
train_sample.node_features.shape#adjacency_lists

(26, 32)

In [9]:
train

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_adjacency_lists',
 '_correct_attachment_point_choices',
 '_correct_edge_choices',
 '_correct_edge_types',
 '_correct_first_node_type_choices',
 '_correct_node_type_choices',
 '_edge_features',
 '_focus_nodes',
 '_graph_property_values',
 '_mol',
 '_node_categorical_features',
 '_node_categorical_num_classes',
 '_node_features',
 '_node_types',
 '_partial_adjacency_lists',
 '_partial_node_categorical_features',
 '_partial_node_features',
 '_type_to_node_to_num_inedges',
 '_valid_attachment_point_choices',
 '_valid_edge_choices',
 '_valid_edge_types',
 'adjacency_lists',
 'correct_attachment_point_choices',
 

In [67]:

for i, step in enumerate(train_sample):
#     if i == 0:
#         break
    pass


In [68]:
i

47

In [57]:
step.correct_edge_choices, step.edge_features

(array([], dtype=float32), array([], shape=(0, 3), dtype=float32))

In [53]:
step.correct_node_type_choices

In [40]:
step.correct_edge_types, step.valid_edge_types

(array([[0, 1, 0]], dtype=int32), array([[1., 1., 1.]]))

In [28]:
# print(train_sample.adjacency_lists)
print(train_sample.node_types)

['C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'O']


In [29]:
print(train_sample.valid_edge_choices)

[array([], shape=(0, 2), dtype=int32), array([[1, 0]], dtype=int32), array([], shape=(0, 2), dtype=int32), array([[2, 0],
       [2, 1]], dtype=int32), array([[2, 0]], dtype=int32), array([[3, 0],
       [3, 2]], dtype=int32), array([[3, 0]], dtype=int32), array([[4, 0],
       [4, 2],
       [4, 3]], dtype=int32), array([[4, 0],
       [4, 2]], dtype=int32), array([[5, 0],
       [5, 2],
       [5, 3],
       [5, 4]], dtype=int32), array([[5, 0],
       [5, 2],
       [5, 3]], dtype=int32), array([[6, 0],
       [6, 2],
       [6, 3],
       [6, 4],
       [6, 5]], dtype=int32), array([[6, 0],
       [6, 2],
       [6, 3],
       [6, 4]], dtype=int32), array([[7, 0],
       [7, 2],
       [7, 3],
       [7, 4],
       [7, 5],
       [7, 6]], dtype=int32), array([[7, 0],
       [7, 2],
       [7, 3],
       [7, 4],
       [7, 5]], dtype=int32), array([[7, 0],
       [7, 3],
       [7, 4],
       [7, 5]], dtype=int32), array([[8, 0],
       [8, 3],
       [8, 4],
       [8, 5],
       [

In [46]:
len(train_sample.partial_adjacency_lists), len(train_sample.partial_node_categorical_features)

(48, 48)

In [44]:
print(train_sample.partial_adjacency_lists)

[[array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)], [array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)], [array([[1, 0],
       [0, 1]], dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)], [array([[1, 0],
       [0, 1]], dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)], [array([[1, 0],
       [2, 1],
       [0, 1],
       [1, 2]], dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)], [array([[1, 0],
       [2, 1],
       [0, 1],
       [1, 2]], dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)], [array([[1, 0],
       [2, 1],
       [0, 1],
       [1, 2]], dtype=int32), array([[3, 2],
       [2, 3]], dtype=int32), array([], shape=(0, 2), dtype=int32)], [array([[1, 0],
       [2, 1],
       [0, 1],
       [1

In [10]:

print(train_sample.partial_node_features[3].shape)

(3, 32)


In [11]:
len(train_sample.partial_node_features)
print(train_sample.partial_node_features[4].shape)
print(train_sample.partial_adjacency_lists[3])
print()
print(train_sample.partial_adjacency_lists[4])

(3, 32)
[array([[1, 0],
       [0, 1]], dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)]

[array([[1, 0],
       [2, 1],
       [0, 1],
       [1, 2]], dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)]


# Porting over from moler_reference/molecule_generation/dataset/trace_dataset.py 

trace_dataset takes in trace samples as they are from the pickle file and constructs a batch of training samplesas follows:
1. It initialises a empty batch of graphs 
2. It starts adding graphs until the batch is as large as it can be (since for a particular generation trace, there might be too many trace steps for us to fit it into a single batch)
3. It also allows us to subsample the trace steps (with some probability discard each of the trace steps)

Since the subsampling needs to be dynamic (at run time) and acts as a kind of augmentation, we can't save the whole graph Data as a .pt file. This needs to be generated on the fly. Hence we can ignore the `process()` function

In [15]:
for trace_step in train_sample:
    print(trace_step)
    break

TraceStep(partial_node_features=array([[ 0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , 12.011,
         4.   ,  4.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ]],
      dtype=float32), partial_node_categorical_features=array([129]), partial_adjacency_lists=[array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)], correct_edge_choices=array([], dtype=float32), valid_edge_choices=array([], shape=(0, 2), dtype=int32), edge_features=array([], shape=(0, 3), dtype=float32), correct_edge_types=array([], shape=(0, 3), dtype=int32), valid_edge_types=array([], shape=(0, 3), dtype=float64), focus_node=0, correct_attachment_point_choice=None, valid_attachment_point_choices=array([], dtype=float64), correct_node_type_choices=['O'])


In [110]:
count= 0
for step2 in train_sample:
    step2.partial_adjacency_lists
    count += 1
    print(count)
    if count == 17:
        break

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [107]:
step2

TraceStep(partial_node_features=array([[ 0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   , 12.011,
         4.   ,  3.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  2.   ,  0.   ,  0.   ,  0.   , 15.999,
         2.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  3.   ,  0.   ,  0.   ,  0.   , 12.011,
         4.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  1.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.  

In [17]:
print(step)

TraceStep(partial_node_features=array([[ 0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   , 12.011,
         4.   ,  3.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  2.   ,  0.   ,  0.   ,  0.   , 15.999,
         2.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  3.   ,  0.   ,  0.   ,  0.   , 12.011,
         4.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  1.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.  

In [18]:
# currently the edge features are from moler_reference/molecule_generation/preprocessing/data_conversion_utils.py
# where we concatenate the distance and topological features 
print(step.edge_features)

[[3. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [2. 0. 0.]]


In [19]:

print(step.partial_adjacency_lists[0].shape)

(10, 2)


In [20]:
step.partial_adjacency_lists

[array([[1, 0],
        [2, 1],
        [4, 3],
        [6, 5],
        [7, 2],
        [0, 1],
        [1, 2],
        [3, 4],
        [5, 6],
        [2, 7]], dtype=int32),
 array([[3, 2],
        [5, 4],
        [7, 6],
        [2, 3],
        [4, 5],
        [6, 7]], dtype=int32),
 array([], shape=(0, 2), dtype=int32)]

# Edge encoding

Currently, there are 3 adjacency lists for each of the 3 bond types and the edge features are topological + distance features as opposed to bond types like in ogb where there are more edge features.

1. Consider adding in the additional edge features during generation of the trace.
2. Consider appending the bond type to the edge features instead of subclassing the data property to add additional adjacency lists

### https://github.com/snap-stanford/ogb/blob/master/ogb/utils/features.py
### Reference repo for getting the bond features including the bond type


# Version 1: Treat all 3 adjacency lists separately by using Heterogeneous Graph Neural Network Operators like https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.RGATConv or https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.HEATConv to pass in the graphs



In [89]:
# from rgat example.py: data must look like this:
from torch_geometric.datasets import Entities

dataset = Entities('/data/ongh0068/', 'AIFB')
data = dataset[0]
data

Data(edge_index=[2, 58086], edge_type=[58086], train_idx=[140], train_y=[140], test_idx=[36], test_y=[36], num_nodes=8285)

In [94]:
dataset.num_relations, len(data.edge_type.unique())

(90, 90)

In [95]:
import torch
from torch_geometric.data import Data
 
x = torch.tensor(step.partial_node_features)
edge_indexes = []
edge_types = []
for i, adj_list in enumerate(step.partial_adjacency_lists):
    print(len(adj_list))
    if len(adj_list) != 0:
        edge_index = torch.tensor(adj_list).T
        edge_indexes += [edge_index]
        edge_types += [i]*len(adj_list)

    
data = Data(
    x = x, 
    edge_index = torch.cat(edge_indexes, 1),
    edge_type = torch.tensor(edge_types),
    random_ting = ['a']*10
)

10
6
0


In [76]:
edge_types

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]

In [71]:
torch.cat(edge_indexes, 1), edge_indexes

(tensor([[1, 2, 4, 6, 7, 0, 1, 3, 5, 2, 3, 5, 7, 2, 4, 6],
         [0, 1, 3, 5, 2, 1, 2, 4, 6, 7, 2, 4, 6, 3, 5, 7]], dtype=torch.int32),
 [tensor([[1, 2, 4, 6, 7, 0, 1, 3, 5, 2],
          [0, 1, 3, 5, 2, 1, 2, 4, 6, 7]], dtype=torch.int32),
  tensor([[3, 5, 7, 2, 4, 6],
          [2, 4, 6, 3, 5, 7]], dtype=torch.int32)])

In [83]:
from torch_geometric.nn import RGATConv

conv1 = RGATConv(in_channels = x.shape[1], out_channels = x.shape[1], num_relations = 3)

In [88]:
conv1(data.x, data.edge_index.long(), data.edge_type)

tensor([[-3.7613,  1.7944,  3.2512,  0.5936, -4.8035,  1.5921, -1.4723, -2.8632,
          4.3359, -1.3874,  0.3438,  1.6469,  3.2785, -1.3352,  2.2742,  2.5232,
         -4.4565, -0.6330,  1.8373, -1.8861,  0.5408, -2.2371,  3.7471,  3.3257,
         -1.3897, -2.9219, -0.7742,  5.1532, -2.4842, -3.1595,  0.1865,  3.5568],
        [-2.6787,  1.3427,  2.4647,  1.7591, -3.9547,  1.5069, -1.4678, -2.1307,
          3.3226, -0.9225, -0.6248,  0.9337,  3.3465, -1.0217,  0.2199,  1.4965,
         -3.3392, -0.7780,  1.5514, -1.3074, -0.1041, -1.7353,  2.4187,  2.4101,
         -0.9328, -1.7731, -1.6437,  3.8357, -1.5283, -2.3272,  0.2179,  2.4367],
        [ 0.8446,  1.4977,  1.0119,  2.2108, -0.9435,  1.5205, -2.8222, -2.4753,
         -0.1914, -3.6746, -1.8493, -0.6793,  3.7787,  0.1027,  0.9275, -1.3210,
          0.7505, -0.3945,  3.4023, -2.9203,  0.9877, -2.7329,  2.1339, -0.6933,
         -1.2505, -1.4371,  1.8314,  0.7723,  0.4515, -1.6701, -3.1665, -0.7783],
        [ 1.7007,  1.4250

# Version 2: Combine all the adjacency lists into 1 (if an edge exists, it exists, and we disregard its type) and then simply append the edge type to the edge features list

In [ ]:
import torch
from torch_geometric.data import Data

x = torch.tensor(step.partial_node_features)
edge_indexes = []
edge_types = []
for i, adj_list in enumerate(step.partial_adjacency_lists):
    print(len(adj_list))
    if len(adj_list) != 0:
        edge_index = torch.tensor(adj_list).T
        edge_indexes += [edge_index]
        edge_types += [i]*len(adj_list)

    
data = Data(
    x = x, 
    edge_index = torch.cat(edge_indexes, 1),
    edge_type = torch.tensor(edge_types),
    random_ting = ['a']*10
)

In [104]:
# step.edge_features
step

TraceStep(partial_node_features=array([[ 0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   , 12.011,
         4.   ,  3.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  2.   ,  0.   ,  0.   ,  0.   , 15.999,
         2.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  3.   ,  0.   ,  0.   ,  0.   , 12.011,
         4.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  1.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.  

In [31]:
from torch_geometric.data import Data
# park all the label information under y since we can handle arbitrary shapes

trace_step.focus_node
trace_step.partial_node_categorical_features
# TODO: implement subsampling


# # x is the node features
data = Data(x=x, edge_index=edge_index, ...)

# # Add additional arguments to `data`:
# data.train_idx = torch.tensor([...], dtype=torch.long)
# data.test_mask = torch.tensor([...], dtype=torch.bool)


TypeError: 'TraceSample' object is not subscriptable

In [24]:
x = torch.tensor(step.partial_node_features)
edge_index = torch.tensor()

(8, 32)

In [25]:
step.partial_adjacency_lists

[array([[1, 0],
        [2, 1],
        [4, 3],
        [6, 5],
        [7, 2],
        [0, 1],
        [1, 2],
        [3, 4],
        [5, 6],
        [2, 7]], dtype=int32),
 array([[3, 2],
        [5, 4],
        [7, 6],
        [2, 3],
        [4, 5],
        [6, 7]], dtype=int32),
 array([], shape=(0, 2), dtype=int32)]

In [ ]:
import os.path as osp

import torch
from torch_geometric.data import Dataset, download_url


class MyOwnDataset(Dataset):
    def __init__(self, root, transform=None, pre_transform=None, pre_filter=None):
        super().__init__(root, transform, pre_transform, pre_filter)

    @property
    def raw_file_names(self):
        return ['some_file_1', 'some_file_2', ...]

    @property
    def processed_file_names(self):
        return ['data_1.pt', 'data_2.pt', ...]

    def download(self):
        # Download to `self.raw_dir`.
        path = download_url(url, self.raw_dir)
        ...

    def process(self):
        idx = 0
        for raw_path in self.raw_paths:
            # Read data from `raw_path`.
            data = Data(...)

            if self.pre_filter is not None and not self.pre_filter(data):
                continue

            if self.pre_transform is not None:
                data = self.pre_transform(data)

            torch.save(data, osp.join(self.processed_dir, f'data_{idx}.pt'))
            idx += 1

    def len(self):
        return len(self.processed_file_names)

    def get(self, idx):
        data = torch.load(osp.join(self.processed_dir, f'data_{idx}.pt'))
        return data

In [ ]:
step

In [22]:
step.partial_adjacency_lists

[array([[1, 0],
        [2, 1],
        [4, 3],
        [6, 5],
        [7, 2],
        [0, 1],
        [1, 2],
        [3, 4],
        [5, 6],
        [2, 7]], dtype=int32),
 array([[3, 2],
        [5, 4],
        [7, 6],
        [2, 3],
        [4, 5],
        [6, 7]], dtype=int32),
 array([], shape=(0, 2), dtype=int32)]

In [29]:
x.size()


torch.Size([3, 1])

In [25]:
x = torch.tensor(trace_step.partial_node_features)


(1, 32)

# examples from zinc and ogb

In [41]:
from torch_geometric.datasets import ZINC

zinc = ZINC(
    root = '/data/ongh0068/',
    subset = True,
)

In [43]:
for data in zinc:
    print(data)
    break

Data(x=[29, 1], edge_index=[2, 64], edge_attr=[64], y=[1])


In [46]:
from ogb.graphproppred import PygGraphPropPredDataset
from torch_geometric.data import DataLoader

# Download and process data at './dataset/ogbg_molhiv/'
dataset = PygGraphPropPredDataset(name = "ogbg-molhiv", root = '/data/ongh0068/')

 
split_idx = dataset.get_idx_split() 
train_loader = DataLoader(dataset[split_idx["train"]], batch_size=32, shuffle=True)

Downloaded 0.00 GB: 100%|█| 3/3 [00:04<00:00,  1.60s


Extracting /data/ongh0068/hiv.zip


Processing...


Loading necessary files...
This might take a while.
Processing graphs...


100%|██████| 41127/41127 [00:00<00:00, 96066.89it/s]


Converting graphs into PyG objects...


100%|██████| 41127/41127 [00:00<00:00, 45014.93it/s]


Saving...


Done!
/data/ongh0068/anaconda3/envs/l1000/lib/python3.9/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


In [48]:
# example representation of molecules from ogb: edges have features of size 3:

# bond type, bond stereo, is_conjugated
for batch in train_loader:
    print(batch.edge_attr)
    break

tensor([[0, 0, 0],
        [0, 0, 0],
        [3, 0, 1],
        ...,
        [0, 0, 1],
        [3, 0, 1],
        [3, 0, 1]])


# TODO:
Currently it looks like the training occurs by telling the model which partial graphs require new nodes or which partial graphs require new edges (since eahc trace step is either of the 2). So how does it do this at sampling time?

Find out under `decode` function from moler_reference/molecule_generation/layers/moler_decoder.py

Seems like with a trained model, we just need to follow the algorithm provided in that file to do so.

In [105]:
# import tf2_gnn.cli_utils.training_utils as training_utils
# import tf2_gnn.cli_utils as cli
# from molecule_generation.dataset.jsonl_moler_trace_dataset import JSONLMoLeRTraceDataset
# from molecule_generation.models.moler_vae import MoLeRVae
# from molecule_generation.models.moler_generator import MoLeRGenerator

# dataset_params = {
#     "graph_properties": {
#         "sa_score": {
#             "type": "regression",
#             "graph_representation_size": 64,
#             "graph_aggregation_num_heads": 8,
#             "graph_aggregation_weighting_fun": "sigmoid",
#             "graph_aggregation_hidden_layers": [],
#             "predictor_mlp_layer_sizes": [],
#             "loss_weight_factor": 0.33,
#         },
#         "clogp": {
#             "type": "regression",
#             "graph_representation_size": 64,
#             "graph_aggregation_num_heads": 8,
#             "graph_aggregation_weighting_fun": "sigmoid",
#             "graph_aggregation_hidden_layers": [],
#             "predictor_mlp_layer_sizes": [32],
#             "loss_weight_factor": 0.33,
#         },
#         "mol_weight": {
#             "type": "regression",
#             "graph_representation_size": 16,
#             "graph_aggregation_num_heads": 4,
#             "graph_aggregation_weighting_fun": "sigmoid",
#             "graph_aggregation_hidden_layers": [],
#             "predictor_mlp_layer_sizes": [],
#             "loss_weight_factor": 0.33,
#         },
#     }
# }
# moler_dataset_params = dict(dataset_params)
# moler_dataset_params["graph_properties"] = dict(dataset_params.get("graph_properties", {}))
# for prop_name, prop_config in dataset_params["graph_properties"].items():
#     moler_dataset_params["graph_properties"][prop_name] = dict(prop_config)
#     moler_dataset_params["graph_properties"][prop_name]["loss_weight_factor"] = 0.02


# cli.register_task(
#     task_name="MoLeR",  # MoLeR VAE
#     dataset_class=JSONLMoLeRTraceDataset,
#     dataset_default_hypers=moler_dataset_params,
#     model_class=MoLeRVae,
#     model_default_hypers={"num_train_steps_between_valid": 5000},
# )
# loaded_model_dataset = training_utils.get_model_and_dataset(
#     msg_passing_implementation='GNN_Edge_MLP',
#     data_path=RichPath.create('/data/ongh0068/l1000/trace_playground'),
#     trained_model_file=None,
#     task_name = 'MoLeRGenerator',
#     cli_data_hyperparameter_overrides = None,
#     cli_model_hyperparameter_overrides = None,
#     folds_to_load={training_utils.DataFold.TRAIN, training_utils.DataFold.VALIDATION},
#     load_weights_only=False,
# )

Trying to load task/model-specific default parameters from /data/ongh0068/anaconda3/envs/l1000/lib/python3.9/site-packages/tf2_gnn/cli_utils/default_hypers/MoLeRGenerator_GNN_Edge_MLP.json ... File not found, using global defaults.


ValueError: Unknown task type 'MoLeRGenerator'

# TODO
1. Construct PyG dataset for reading the traces from the pickle files => process them into PyG Data objects + the preprocessing done in the tf datasets
2. Look into the training code and modify it

In [18]:
import os.path as osp

import torch
from torch_geometric.data import Dataset


class GenericMoLerTraceDataset(Dataset):
    def __init__(
        self, 
        root, 
        trace_dataset_folder_path,
        transform=None, 
        pre_transform=None, 
        pre_filter=None,
    ):
        """
        Initialise trace dataset.
        :param trace_dataset_folder_path: The path to the train, validation or test folder that 
        contains the pickle files with the generation trace of each molecule.
        """
        super().__init__(root, transform, pre_transform, pre_filter)
        self._trace_dataset_folder_path = trace_dataset_folder_path

    @property
    def raw_file_names(self):
        """
        File names of MoLeR style jsonl trace data.
        """
        return os.listdir(self._trace_dataset_folder_path)

    @property
    def processed_file_names(self):
        return ['data_1.pt', 'data_2.pt', ...]
    
    def process(self):
        """Preprocess and save the PyG graph data if it has not been generated."""
        idx = 0
        for raw_path in self.raw_file_names:
            # Read data from `raw_path`.
            data = Data(...)

            if self.pre_filter is not None and not self.pre_filter(data):
                continue

            if self.pre_transform is not None:
                data = self.pre_transform(data)

            torch.save(data, osp.join(self.processed_dir, f'data_{idx}.pt'))
            idx += 1

    def len(self):
        return len(self.processed_file_names)

    def get(self, idx):
        data = torch.load(osp.join(self.processed_dir, f'data_{idx}.pt'))
        return data

'/data/ongh0068/l1000/moler_reference'

In [3]:
from typing import Dict, List, Optional, Tuple, TypeVar, Union
import pathlib
DataEntry = Dict[str, str]
SmilesDataSet = List[DataEntry]
Pathlike = Union[str, pathlib.Path]
def _read_data(path: Pathlike) -> SmilesDataSet:
    with open(path) as f:
        data = f.readlines()

    data = [{"SMILES": x.strip()} for x in data]
    return data

In [14]:
data = _read_data('/data/ongh0068/l1000/raw_smiles_playground/train.smiles')

In [10]:
import enum
import logging

logger = logging.getLogger(__name__)

class DatasetPath(enum.Enum):
    """The directory with a data set should contain the following files."""

    TRAIN = "train.smiles"
    VALID = "valid.smiles"
    TEST = "test.smiles"
def load_smiles_data(
    data_path: Pathlike,
    n_datapoints: Optional[int] = None,
) -> Tuple[SmilesDataSet, SmilesDataSet, SmilesDataSet]:
    """Loads data sets from a given directory.

    Args:
        data_path: a directory with the train, validation and test SMILES files (structure described in DatasetPath)
        n_datapoints: the number of molecules to be used from the training data set. The validation and test
            data sets are rescaled accordingly. If None, all samples from each data set are taken

    Returns:
        training data set
        validation data set
        test data set
    """
    # Load the training data set
    data_path = pathlib.Path(data_path)
    train_path = data_path / DatasetPath.TRAIN.value
    train_data: SmilesDataSet = _read_data(train_path)

    # Log the information about the training data set
    num_train = len(train_data)
    logger.info(f"Read {num_train} datapoints from {train_path}")

    # Read validation and test data sets
    valid_data: SmilesDataSet = _read_data(data_path / DatasetPath.VALID.value)
    test_data: SmilesDataSet = _read_data(data_path / DatasetPath.TEST.value)

    # If num_datapoints is specified, we truncate all data sets proportionally
    if n_datapoints is not None:
        if n_datapoints <= 0:
            raise ValueError("num_datapoints must be positive.")
        # Get exactly num_datapoints for the training set
        train_data = train_data[:n_datapoints]
        ratio = n_datapoints / num_train

        # Truncate the validation and test data sets proportionally
        valid_data = _get_first_samples(valid_data, ratio)
        test_data = _get_first_samples(test_data, ratio)

    if not test_data or not valid_data:
        logger.warning("Test or valid set contains no points; increase num_datapoints")
        raise ValueError("Test or valid data sets are empty; increase num_datapoints")

    return train_data, valid_data, test_data

In [11]:
load_smiles_data('/data/ongh0068/l1000/raw_smiles_playground')

([{'SMILES': 'COC(=O)c1ccc2c(c1)N(Cc1ccccc1)C(=O)c1ccccc1S2(=O)=O'},
  {'SMILES': 'COc1cccc2c1CCCC2CN(C)CCc1ccc2c(c1)CCO2'},
  {'SMILES': 'COc1ccc2c3c1OC1CC(O)C=CC31CCN(C)C2'},
  {'SMILES': 'CCOc1ccc(NC(=O)c2c(NC(=O)c3cccc(C)c3)sc3c2CCC3)cc1'},
  {'SMILES': 'O=C(c1cccc(Cl)c1)N1CCC(NCc2ccnc3ccccc23)CC1Cc1ccccc1'},
  {'SMILES': 'Clc1cccc(Cl)c1Nc1nc(C(Cl)(Cl)Cl)nc2ccccc12'},
  {'SMILES': 'CCCCCCC=CC(C)=O'},
  {'SMILES': 'O=C(Cn1cc(N=C(O)c2cnn3cccnc23)c(-c2cc(Cl)ccc2OC(F)F)n1)N1CCC(N2CC3CC2CO3)CC1'},
  {'SMILES': 'CC(=O)Nc1nc(-c2ccc([N+](=O)[O-])cc2)cs1'},
  {'SMILES': 'COC(=O)CCCCCN1C(=O)NC(C2CC2)C(C(=O)OCc2ccccc2)=C1C'},
  {'SMILES': 'COc1ccc(-c2cc(C(F)(F)F)c(C#N)c(SCC(=O)O)n2)cc1'},
  {'SMILES': 'C=C1c2ccccc2Oc2nc3nc(N)c(C#N)c(N)c3c(N)c21'},
  {'SMILES': 'CSc1nc(N)nc2c1ncn2CC(=O)NCC(c1ccccc1)c1ccccc1'},
  {'SMILES': 'COc1cc2nc(Nc3cccc(C)c3)nc(N)c2cc1OC'},
  {'SMILES': 'O=C(O)C(CC1CC1)N1CC(CN2CCC(c3cnc(Cc4ccccc4)o3)CC2)C(c2ccccc2)C1'},
  {'SMILES': 'CCOC(=O)c1sc2nc(SCC(=O)NCc3ccccc3)n(Cc