In [17]:
%load_ext autoreload
%autoreload 2
from model import BaseModel
from dataset import MolerDataset, MolerData
from utils import pprint_pyg_obj
from torch_geometric.loader import DataLoader
import torch
from model_utils import get_params

dataset = MolerDataset(
    root = '/data/ongh0068', 
    raw_moler_trace_dataset_parent_folder = '/data/ongh0068/guacamol/trace_dir',
    output_pyg_trace_dataset_parent_folder = '/data/ongh0068/l1000/test_thread2',
    split = 'valid_0',
)
loader = DataLoader(dataset, batch_size=2, shuffle=False, follow_batch = [
    'correct_edge_choices',
    'correct_edge_types',
    'valid_edge_choices',
    'valid_attachment_point_choices',
    'correct_attachment_point_choice',
    'correct_node_type_choices',
    'original_graph_x',
    'correct_first_node_type_choices',
])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [43]:
for batch2 in loader:
    break
    

In [52]:
batch2.correct_edge_choices_batch, batch2.correct_edge_choices

(tensor([   0,    0,    1,  ..., 1999, 1999, 1999]),
 tensor([0., 0., 0.,  ..., 0., 0., 1.]))

In [51]:
batch2.valid_edge_choices

tensor([[    7,     0],
        [    7,     5],
        [   16,     8],
        ...,
        [30841, 30834],
        [30841, 30839],
        [30841, 30840]], dtype=torch.int32)

In [48]:
pprint_pyg_obj(batch2)

x: torch.Size([30842, 59])
edge_index: torch.Size([2, 91640])
original_graph_edge_type: torch.Size([178022])
original_graph_node_categorical_features: torch.Size([56264])
focus_node: torch.Size([2000])
edge_type: torch.Size([91640])
edge_features: torch.Size([13461, 3])
correct_edge_choices: torch.Size([13461])
correct_edge_choices_batch: torch.Size([13461])
correct_edge_choices_ptr: torch.Size([2001])
num_correct_edge_choices: torch.Size([2000])
stop_node_label: torch.Size([2000])
valid_edge_choices: torch.Size([13461, 2])
valid_edge_choices_batch: torch.Size([13461])
valid_edge_choices_ptr: torch.Size([2001])
valid_edge_types: torch.Size([1013, 3])
correct_edge_types: torch.Size([1013, 3])
correct_edge_types_batch: torch.Size([1013])
correct_edge_types_ptr: torch.Size([2001])
partial_node_categorical_features: torch.Size([30842])
correct_attachment_point_choice: torch.Size([95])
correct_attachment_point_choice_batch: torch.Size([95])
correct_attachment_point_choice_ptr: torch.Size([2

In [9]:
batch.sa_score.shape[0]

1000

In [15]:
torch.cat((batch.ptr, batch.ptr[1:]+batch.ptr[-1]))[998:1004]

tensor([15816, 15834, 15852, 15860, 15869, 15878])

In [16]:
batch.ptr

tensor([    0,     8,    17,  ..., 15816, 15834, 15852])

In [4]:
# for key in vars(batch)["_store"].keys():
#     if key.startswith("_"):
#         continue
#     print((batch[key] == dataset[0][key]).all())

In [5]:
pprint_pyg_obj(dataset[0]), dataset[0].correct_first_node_type_choices_ptr[999:1005]

x: torch.Size([15852, 59])
edge_index: torch.Size([2, 47220])
original_graph_edge_type: torch.Size([90598])
original_graph_node_categorical_features: torch.Size([28616])
focus_node: torch.Size([1000])
edge_type: torch.Size([47220])
edge_features: torch.Size([7104, 3])
correct_edge_choices: torch.Size([7104])
correct_edge_choices_batch: torch.Size([7104])
correct_edge_choices_ptr: torch.Size([1001])
num_correct_edge_choices: torch.Size([1000])
stop_node_label: torch.Size([1000])
valid_edge_choices: torch.Size([7104, 2])
valid_edge_choices_batch: torch.Size([7104])
valid_edge_choices_ptr: torch.Size([1001])
valid_edge_types: torch.Size([510, 3])
correct_edge_types: torch.Size([510, 3])
correct_edge_types_batch: torch.Size([510])
correct_edge_types_ptr: torch.Size([1001])
partial_node_categorical_features: torch.Size([15852])
correct_attachment_point_choice: torch.Size([42])
correct_attachment_point_choice_batch: torch.Size([42])
correct_attachment_point_choice_ptr: torch.Size([1001])
cor

(None, tensor([ 999, 1000]))

In [6]:
pprint_pyg_obj(batch), batch.correct_first_node_type_choices_ptr[999:1005]

x: torch.Size([15852, 59])
edge_index: torch.Size([2, 47220])
original_graph_edge_type: torch.Size([90598])
original_graph_node_categorical_features: torch.Size([28616])
focus_node: torch.Size([1000])
edge_type: torch.Size([47220])
edge_features: torch.Size([7104, 3])
correct_edge_choices: torch.Size([7104])
correct_edge_choices_batch: torch.Size([7104])
correct_edge_choices_ptr: torch.Size([1001])
num_correct_edge_choices: torch.Size([1000])
stop_node_label: torch.Size([1000])
valid_edge_choices: torch.Size([7104, 2])
valid_edge_choices_batch: torch.Size([7104])
valid_edge_choices_ptr: torch.Size([1001])
valid_edge_types: torch.Size([510, 3])
correct_edge_types: torch.Size([510, 3])
correct_edge_types_batch: torch.Size([510])
correct_edge_types_ptr: torch.Size([1001])
partial_node_categorical_features: torch.Size([15852])
correct_attachment_point_choice: torch.Size([42])
correct_attachment_point_choice_batch: torch.Size([42])
correct_attachment_point_choice_ptr: torch.Size([1001])
cor

(None, tensor([ 999, 1000]))

In [2]:
import gzip
import pickle
file_path = '/data/ongh0068/l1000/test_thread2/valid_0/0_nsteps_1000.pkl.gz'
with gzip.open(file_path, "rb") as f:
    data = pickle.load(f)

In [3]:
data.to('cuda:1')

MolerDataBatch(x=[16553, 59], edge_index=[2, 49271], original_graph_edge_type=[94113], original_graph_node_categorical_features=[29761], focus_node=[1000], edge_type=[49271], edge_features=[8113, 3], correct_edge_choices=[8113], correct_edge_choices_batch=[8113], correct_edge_choices_ptr=[1001], num_correct_edge_choices=[1000], stop_node_label=[1000], valid_edge_choices=[8113, 2], valid_edge_choices_batch=[8113], valid_edge_choices_ptr=[1001], valid_edge_types=[518, 3], correct_edge_types=[518, 3], correct_edge_types_batch=[518], correct_edge_types_ptr=[1001], partial_node_categorical_features=[16553], correct_attachment_point_choice=[47], correct_attachment_point_choice_batch=[47], correct_attachment_point_choice_ptr=[1001], correct_node_type_choices=[475, 166], correct_node_type_choices_batch=[475], correct_node_type_choices_ptr=[1001], correct_first_node_type_choices=[1000, 166], correct_first_node_type_choices_batch=[1000], correct_first_node_type_choices_ptr=[1001], sa_score=[1000

In [4]:
from model import BaseModel

params = get_params(dataset)
model = BaseModel(params, dataset).to('cuda:1')



In [5]:
model

BaseModel(
  (_full_graph_encoder): GraphEncoder(
    (_embed): Embedding(166, 64)
    (_model): GenericGraphEncoder(
      (_first_layer): GCNConv(123, 64)
      (_encoder_layers): ModuleList(
        (0): GCNConv(64, 64)
        (1): GCNConv(64, 64)
        (2): GCNConv(64, 64)
        (3): GCNConv(64, 64)
        (4): GCNConv(64, 64)
        (5): GCNConv(64, 64)
        (6): GCNConv(64, 64)
        (7): GCNConv(64, 64)
        (8): GCNConv(64, 64)
        (9): GCNConv(64, 64)
        (10): GCNConv(64, 64)
        (11): GCNConv(64, 64)
      )
      (_softmax_aggr): SoftmaxAggregation(learn=True)
    )
  )
  (_partial_graph_encoder): PartialGraphEncoder(
    (_embed): Embedding(166, 64)
    (_model): GenericGraphEncoder(
      (_first_layer): GCNConv(124, 64)
      (_encoder_layers): ModuleList(
        (0): GCNConv(64, 64)
        (1): GCNConv(64, 64)
        (2): GCNConv(64, 64)
        (3): GCNConv(64, 64)
        (4): GCNConv(64, 64)
        (5): GCNConv(64, 64)
        (6): GCNC

In [7]:
moler_output = model._run_step(data)

loss = model.compute_loss(moler_output, data)

In [ ]:
# tmp = []

# for i, batch in enumerate(loader):
#     tmp += [batch]
#     if i == 6:
#         break
    

In [ ]:
from torch_geometric.data import Batch
%load_ext autoreload
%autoreload 2
super_batch = Batch.from_data_list([i for i in tmp[3:6]], follow_batch = [
    'correct_edge_choices',
    'correct_edge_types',
    'valid_edge_choices',
    'valid_attachment_point_choices',
    'correct_attachment_point_choice',
    'correct_node_type_choices',
    'original_graph_x',
    'correct_first_node_type_choices',
    # pick attachment points
    'candidate_attachment_points',
    # pick edge
    'candidate_edge_targets'
])


super_loader = DataLoader(tmp, batch_size=4, shuffle=False, follow_batch = [
    'correct_edge_choices',
    'correct_edge_types',
    'valid_edge_choices',
    'valid_attachment_point_choices',
    'correct_attachment_point_choice',
    'correct_node_type_choices',
    'original_graph_x',
    'correct_first_node_type_choices'
])


for super_batch in super_loader:
    break

In [ ]:
super_batch.focus_node

In [25]:
file_path = '/data/ongh0068/l1000/test_thread2/valid_0/valid_0_nsteps_6022.pkl.gz'

import gzip 
import pickle
with gzip.open(file_path, "rb") as f:
    print(f)
    tmp = pickle.load(f)


<gzip _io.BufferedReader name='/data/ongh0068/l1000/test_thread2/valid_0/valid_0_nsteps_6022.pkl.gz' 0x7f1b3a1f2730>


In [26]:
tmp

MolerDataBatch(x=[98223, 59], edge_index=[2, 293253], original_graph_edge_type=[556981], original_graph_node_categorical_features=[175911], focus_node=[6022], edge_type=[293253], edge_features=[44973, 3], correct_edge_choices=[44973], correct_edge_choices_batch=[44973], correct_edge_choices_ptr=[6023], num_correct_edge_choices=[6022], stop_node_label=[6022], valid_edge_choices=[44973, 2], valid_edge_choices_batch=[44973], valid_edge_choices_ptr=[6023], valid_edge_types=[3093, 3], correct_edge_types=[3093, 3], correct_edge_types_batch=[3093], correct_edge_types_ptr=[6023], partial_node_categorical_features=[98223], correct_attachment_point_choice=[279], correct_attachment_point_choice_batch=[279], correct_attachment_point_choice_ptr=[6023], correct_node_type_choices=[2874, 166], correct_node_type_choices_batch=[2874], correct_node_type_choices_ptr=[6023], correct_first_node_type_choices=[6022, 166], correct_first_node_type_choices_batch=[6022], correct_first_node_type_choices_ptr=[6023]